name: Texture
version: 1.0
main: event.texture.Texture
database: true
api-version: 1.14
description: 이벤트용으로 제작된 아이템을 인식하여 다른 텍스쳐로 바꿔주는 플러그인
commands:
  이벤트추가:
    description: /이벤트추가 [이벤트이름], [이벤트코드(이벤트아이템에 적용할 CustomModelData)] 진행할 이벤트를 추가합니다.
  이벤트활성화:
    description: /이벤트활성화 [이벤트이름] 해당 이벤트를 활성화 합니다.
  이벤트비활성화:
    description: /이벤트비활성화 [이벤트이름] 해당 이벤트를 비활성화 합니다.
  이벤트아이템:
    description: /이벤트아이템 추가 [이벤트이름] = 손에 든 아이템을 이벤트아이템에 추가합니다. /이벤트아이템 제거 [이벤트이름] = 손에 든 아이템을 이벤트아이템에서 제거합니다. /이벤트아이템 초기화 [이벤트이름] = 등록된 모든 이벤트아이템을 제거합니다.
  이벤트보상:
    description: /이벤트보상 획득 [이벤트이름] = 해당 이벤트에 등록된 아이템을 지급하는 인벤토리를 오픈합니다.
  이벤트목록:
    description: /이벤트목록 = 이벤트 목록을 출력합니다.